name: Deploy to Vercel

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Project Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        if: github.ref == 'refs/heads/main'

      - name: Pull Vercel Project Information (Preview)
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        if: github.ref != 'refs/heads/main'

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        if: github.ref == 'refs/heads/main'

      - name: Build Project Artifacts (Preview)
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        if: github.ref != 'refs/heads/main'

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --prod
        if: github.ref == 'refs/heads/main'

      - name: Deploy Project Artifacts to Vercel (Preview)
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        if: github.ref != 'refs/heads/main'
